# Sorted based on priority

# Startup
source = ~/.config/hypr/modules/startup/init.conf

# Environments
source = ~/.config/hypr/modules/environments.conf

# I/O devices
source = ~/.config/hypr/modules/devices/init.conf

# Keybinds
source = ~/.config/hypr/modules/keybinds/init.conf

# Customizations (will rework)
source = ~/.config/hypr/style.conf

# Window rules
source = ~/.config/hypr/modules/windowrules/init.conf

xwayland {
    force_zero_scaling = true
}

