general {
    gaps_in = 4
    gaps_out = 4

    border_size = 2

    col.active_border = rgba(A078FFFF)
    col.inactive_border = rgba(C1ACFFFF)

    resize_on_border = true

    allow_tearing = false

    layout = dwindle
    
}

decoration {
    rounding = 4 

    active_opacity = 1.0
    inactive_opacity = 1.0

    blur {
        enabled = yes
        size = 6
        passes = 3
        new_optimizations = on
        ignore_opacity = on
    }
}

# Blur waybar
layerrule = blur on, match:namespace waybar
# Blur wlogout
layerrule = blur on, match:namespace alacritty 


animations {
    enabled = false 

    bezier = ease, 0.1, 0.1, 0.25, 1.0
    bezier = overshot, 0.1, 0.99, 0, 1.0

    animation = windows, 1, 5,  overshot, gnomed
    animation = windowsOut, 1, 5, ease, slide bottom
    animation = windowsMove, 1, 5, overshot, slide

    animation = layers, 1, 5, ease, gnomed
    animation = fade, 1, 3, ease
    animation = border, 1, 2, ease
    animation = workspaces, 1, 5, overshot, slide
} 
