source = ~/.config/hypr/modules/keybinds/summons.conf
source = ~/.config/hypr/modules/keybinds/screenshots.conf
source = ~/.config/hypr/modules/keybinds/clipboard.conf
source = ~/.config/hypr/modules/keybinds/workspaces.conf
source = ~/.config/hypr/modules/keybinds/windows.conf
source = ~/.config/hypr/modules/keybinds/mouse.conf
source = ~/.config/hypr/modules/keybinds/special_keys.conf
source = ~/.config/hypr/modules/keybinds/theme_switcher.conf
