$terminal = alacritty
$browser = helium-browser
$menu = rofi -show drun

# Terminal
bind = SUPER, RETURN, exec, $terminal

# Kill Program
bind = SUPER, Q, killactive,

# Browser
bind = SUPER, B, exec, $browser

# Menu
bind = SUPER, SPACE, exec, $menu
