# Focus
bind = SUPER, left, movefocus, l
bind = SUPER, right, movefocus, r
bind = SUPER, up, movefocus, u
bind = SUPER, down, movefocus, d

# Kill Program
bind = SUPER, Q, killactive

# Fullscreen
bind = SUPER, F, fullscreen

# Toggle Floating
bind = SUPER SHIFT, F, togglefloating

# Toggle 
bind = SUPER, J, layoutmsg, swapsplit
bind = SUPER SHIFT, J, layoutmsg, togglesplit

# Pseudo
bind = SUPER, P, pseudo
