input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0.35 # -1.0 - 1.0, 0 means no modification.
    accel_profile = flat
    touchpad {
        natural_scroll = false
    }
    tablet {
      output = eDP-1
      region_position = 0 0
      region_size = 0 0 
    }
}
