exec-once = cliphist wipe
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-one = wl-copy --watch cliphist store
exec-once = wl-clip-persist --clipboard regular
