source = ~/.config/hypr/modules/startup/polkit.conf
source = ~/.config/hypr/modules/startup/notifications.conf
source = ~/.config/hypr/modules/startup/clipboard.conf
source = ~/.config/hypr/modules/startup/waybar.conf
source = ~/.config/hypr/modules/startup/wallpaper.conf
